spring:
  main:
    web-application-type: none
    keep-alive: true
  application:
    name: warehouse-service

application:
  sensors:
    humidity:
      port: 3355
    temperature:
      port: 3344